# Generated by Django 6.0 on 2025-12-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_description_productcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='prodoct',
            new_name='product',
        ),
    ]
